In [73]:
import numpy as np
# !pip install numpy

In [38]:
my_list = [10,20,30,40,50]

In [39]:
np.array(my_list)

array([10, 20, 30, 40, 50])

In [40]:
my_numpy_array = np.array(my_list)

In [41]:
my_numpy_array

array([10, 20, 30, 40, 50])

In [42]:
type(my_numpy_array)

numpy.ndarray

In [43]:
my_numpy_array.max()

np.int64(50)

In [44]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [45]:
np.random.random(5)
# 0 ile 1 arasında rastgele 5 elemanlı bir numpy dizisi oluşturulur!

array([0.65976784, 0.46293613, 0.33169927, 0.47688968, 0.75170946])

In [46]:
# array arithmetic

In [47]:
myList1 = [1,2]
myList2 = [2,3]

In [48]:
myList1 + myList2

[1, 2, 2, 3]

In [49]:
myNumpyArray1 = np.array(myList1)
myNumpyArray2 = np.array(myList2)

In [50]:
myNumpyArray1 + myNumpyArray2

array([3, 5])

In [51]:
# 1 + 2 = 3
# 2 + 3 = 5 yazdı...

In [52]:
myNumpyArray1 * myNumpyArray2

array([2, 6])

In [53]:
myNumpyArray1 / myNumpyArray2

array([0.5       , 0.66666667])

In [54]:
myNumpyArray1 * 5 

array([ 5, 10])

In [55]:
myList1 * 5

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [56]:
# ARADAKİ FARKA DİKKAT ET !!!!

In [57]:
otherArray = np.array([10,20,30,40,50,60,70,80,90])

In [58]:
otherArray.min()

np.int64(10)

In [59]:
otherArray.sum()

np.int64(450)

In [60]:
# myNumpyArray1 + otherArray = HATA VERİR!
# çünkü birinde 2 eleman diğerinde 9 eleman var. Karşılıklı olarak toplanırlardı !!!!!

# arange & indexing

In [61]:
np.arange(0,20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [62]:
# Listelerdeki range ile aynı mantık. Numpy içinde 'arange' olarak geçer!

In [63]:
npArray = np.arange(0,10)

In [64]:
npArray

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
npArray[0]

np.int64(0)

In [66]:
npArray[-1]

np.int64(9)

In [67]:
npArray[1:5:]

array([1, 2, 3, 4])

In [68]:
npArray[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [69]:
npArray[2:7:2] # slicing işlemleri de geçerli!

array([2, 4, 6])

In [70]:
np.random.randn(4)

array([-1.78529947, -0.10403588, -0.29415178, -1.54414267])

In [71]:
np.random.randn(4,4)

array([[-0.57103602, -1.14115426, -0.79715459, -0.54534611],
       [-0.52496867,  0.8571215 , -0.41710128,  0.60627282],
       [ 0.11650561, -0.37875933,  0.69890912, -0.040562  ],
       [-2.04556263, -0.43303915,  0.06656263, -0.95984867]])

In [72]:
np.random.randint(1,300,5)

array([262, 170, 259, 262,   8], dtype=int32)