In [47]:
import numpy as np

In [91]:
my_matrix = [[10,20],[30,40]]

In [49]:
my_matrix[0]

[10, 20]

In [50]:
my_matrix[1]

[30, 40]

In [51]:
my_matrix[0][1]

20

In [52]:
# row - column

In [53]:
numpy_matrix = np.array([[10,20],[30,40]])

In [54]:
numpy_matrix

array([[10, 20],
       [30, 40]])

In [55]:
numpy_matrix[1][0]

np.int64(30)

In [56]:
numpy_matrix.sum()

np.int64(100)

In [57]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [58]:
np.zeros((3,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [59]:
np.random.random((2,4))

array([[0.27171724, 0.34678366, 0.87692888, 0.18671918],
       [0.67206247, 0.68368769, 0.94826564, 0.96928189]])

# matrix arithmetic

In [60]:
first_matrix = np.array([[10,20],[30,40]])
second_matrix = np.array([[50,60],[70,80]])

In [61]:
first_matrix + second_matrix 

array([[ 60,  80],
       [100, 120]])

In [62]:
third_matrix = np.array([5,5])

In [63]:
first_matrix + third_matrix

array([[15, 25],
       [35, 45]])

In [64]:
fourth_matrix = np.array([1,2,3,4,5,6])

In [65]:
#first_matrix + fourth_matrix   hata verir!!!! 

In [66]:
first_matrix * 2

array([[20, 40],
       [60, 80]])

In [67]:
first_matrix / 2

array([[ 5., 10.],
       [15., 20.]])

In [68]:
third_matrix = np.array([[10],[20]])

In [69]:
third_matrix

array([[10],
       [20]])

In [70]:
third_matrix.shape

(2, 1)

In [71]:
# 2 row , 1 column

In [72]:
first_matrix.shape

(2, 2)

In [73]:
first_matrix + third_matrix 

array([[20, 30],
       [50, 60]])

In [74]:
# Kolon kolon toplama yapılıyor beklediğimiz gibi...

# Matrix Çarpımları

In [75]:
first_matrix

array([[10, 20],
       [30, 40]])

In [76]:
second_matrix

array([[50, 60],
       [70, 80]])

In [77]:
first_matrix * second_matrix

array([[ 500, 1200],
       [2100, 3200]])

In [78]:
# dot product

In [79]:
# birinin kolon sayısı ile diğerinin row sayısının birbirine eşit olması gerekiyor !!!
# https://jalammar.github.io/visual-numpy

In [80]:
first_matrix = np.array([[10,20,30]])

In [81]:
first_matrix

array([[10, 20, 30]])

In [82]:
first_matrix.shape

(1, 3)

In [83]:
second_matrix = np.array([[2,3],[2,3],[2,3]])

In [84]:
second_matrix

array([[2, 3],
       [2, 3],
       [2, 3]])

In [85]:
second_matrix.shape

(3, 2)

In [86]:
# first_matrix 1 row 3 kolon , second_matrix 3 row 2 kolon ; bunları dot product yapabiliriz -->

In [87]:
#first_matrix * second_matrix

# birisi 1 e 3 diğeri 3 e 2 !!!! HATA VERİR

In [88]:
result_matrix = first_matrix.dot(second_matrix)

In [89]:
result_matrix

array([[120, 180]])

In [90]:
result_matrix.shape

(1, 2)