In [1]:
import numpy as np

In [3]:
newArray = np.random.randint(1,100,20)

In [4]:
newArray

array([41, 69, 95, 23, 35, 28, 59,  1, 12, 48, 26, 87, 15, 36, 94, 55, 83,
       13, 28, 71], dtype=int32)

In [5]:
newArray > 25

array([ True,  True,  True, False,  True,  True,  True, False, False,
        True,  True,  True, False,  True,  True,  True,  True, False,
        True,  True])

In [6]:
newArray[newArray>50]

array([69, 95, 59, 87, 94, 55, 83, 71], dtype=int32)

# transpose & reshape

In [9]:
matrix_array = np.array([[10,20],[30,40],[50,60]])

In [10]:
matrix_array

array([[10, 20],
       [30, 40],
       [50, 60]])

In [11]:
matrix_array.transpose()

array([[10, 30, 50],
       [20, 40, 60]])

In [12]:
# row ve column yerlerini değiştiriyor...

In [13]:
matrix_array.T

array([[10, 30, 50],
       [20, 40, 60]])

In [14]:
# .T ile de transpose işlemini yapabiliyoruz !

In [15]:
random_array = np.random.random((6,1))

In [16]:
random_array

array([[0.66403831],
       [0.68104665],
       [0.35211623],
       [0.05365459],
       [0.43021855],
       [0.55190673]])

In [17]:
random_array.shape

(6, 1)

In [18]:
random_array.reshape(2,3)

array([[0.66403831, 0.68104665, 0.35211623],
       [0.05365459, 0.43021855, 0.55190673]])

In [19]:
random_array.reshape(3,2)

array([[0.66403831, 0.68104665],
       [0.35211623, 0.05365459],
       [0.43021855, 0.55190673]])

In [20]:
# z-score

In [21]:
data = np.array([10,12,13,15,18,25,100,105])

In [22]:
#outlier

In [23]:
mean = data.mean()

In [24]:
mean

np.float64(37.25)

In [25]:
#standart sapma
std = np.std(data)

In [26]:
std

np.float64(37.9333296719389)

In [27]:
z_scores = (data-mean)/std

In [28]:
z_scores

array([-0.71836562, -0.66564154, -0.6392795 , -0.58655542, -0.50746929,
       -0.322935  ,  1.65421809,  1.78602829])

In [30]:
data[z_scores>1]

array([100, 105])

In [31]:
# math equations

In [32]:
# 2x + 3y = 8 and 5x + 7y = 19

In [33]:
# coefficient - katsayılar

In [35]:
A = np.array([[2,3],[5,7]])

In [36]:
# constants - sabitler

In [38]:
B = np.array([8,19])

In [39]:
solution = np.linalg.solve(A,B)

In [40]:
solution

array([1., 2.])